-- MySQL Script generated by MySQL Workbench
-- 03/17/17 20:38:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Escala
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escala
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escala` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Escala` ;

-- -----------------------------------------------------
-- Table `Escala`.`Recruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escala`.`Recruta` (
  `Cod` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Data_Nasc` VARCHAR(45) NULL,
  `RG` VARCHAR(20) NOT NULL,
  `CPF` VARCHAR(20) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  `Telefone_Recado` VARCHAR(45) NULL,
  `Nome_Mae` VARCHAR(45) NULL,
  `Nome_Pai` VARCHAR(45) NULL,
  `Nome_Guerra` VARCHAR(45) NULL,
  `Numero_Matricula` INT NULL,
  `Numero_Chamada` INT NULL,
  `Ano_Instrucao` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
